# Generated by Django 6.0 on 2025-12-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_trip', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='radius',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
