# Generated by Django 6.0 on 2025-12-07 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_trip', '0004_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('route_data', models.JSONField(help_text='The trip to_json() method')),
            ],
        ),
    ]
