# Generated by Django 6.0 on 2025-12-06 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('parola', models.CharField(max_length=255)),
                ('nrTelefon', models.CharField(blank=True, max_length=20, null=True)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('latitudine', models.FloatField()),
                ('longitudine', models.FloatField()),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('parola', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProducatoriCategorii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categorie')),
                ('idProducator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producator')),
            ],
            options={
                'unique_together': {('idProducator', 'idCategorie')},
            },
        ),
    ]
