# Generated by Django 6.0 on 2025-12-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Categorii',
        ),
        migrations.RenameModel(
            old_name='Producator',
            new_name='Producatori',
        ),
        migrations.RenameModel(
            old_name='Utilizator',
            new_name='Utilizatori',
        ),
    ]
