# Generated by Django 6.0 on 2025-12-06 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_categorie_categorii_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('pret', models.FloatField(blank=True, null=True)),
                ('tip', models.CharField(blank=True, max_length=50, null=True)),
                ('producator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produse', to='app.producatori')),
            ],
        ),
    ]
