# Generated by Django 6.0 on 2025-12-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_produse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorii',
            options={'verbose_name': 'Categorie', 'verbose_name_plural': 'Categorii'},
        ),
        migrations.AlterModelOptions(
            name='producatori',
            options={'verbose_name': 'Producator', 'verbose_name_plural': 'Producatori'},
        ),
        migrations.AlterModelOptions(
            name='producatoricategorii',
            options={'verbose_name': 'ProducatorCategorie', 'verbose_name_plural': 'ProducatoriCategorii'},
        ),
        migrations.AlterModelOptions(
            name='produse',
            options={'verbose_name': 'Produs', 'verbose_name_plural': 'Produse'},
        ),
        migrations.AlterModelOptions(
            name='utilizatori',
            options={'verbose_name': 'Utilizator', 'verbose_name_plural': 'Utilizatori'},
        ),
        migrations.RemoveField(
            model_name='produse',
            name='descriere',
        ),
        migrations.RemoveField(
            model_name='produse',
            name='tip',
        ),
        migrations.AddField(
            model_name='producatori',
            name='categorii',
            field=models.ManyToManyField(related_name='producatori', through='app.ProducatoriCategorii', to='app.categorii'),
        ),
        migrations.AlterField(
            model_name='produse',
            name='pret',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
