# Generated by Django 6.0 on 2025-12-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_categorii_options_alter_producatori_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produse',
            old_name='producator',
            new_name='idProducator',
        ),
        migrations.AlterField(
            model_name='produse',
            name='pret',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='categorii',
            table='Categorii',
        ),
        migrations.AlterModelTable(
            name='producatori',
            table='Producatori',
        ),
        migrations.AlterModelTable(
            name='producatoricategorii',
            table='ProducatoriCategorii',
        ),
        migrations.AlterModelTable(
            name='produse',
            table='Produse',
        ),
        migrations.AlterModelTable(
            name='utilizatori',
            table='Utilizatori',
        ),
    ]
